BUILDLIB:=TYRICO

CLEAN:
	-system "DLTPGM PGM(${BUILDLIB}/ILEBRIDGEC)"
	-system "DLTMOD MODULE(${BUILDLIB}/ILEBRIDGEC)"
	-system "DLTMOD MODULE(${BUILDLIB}/ILEBRIDGEL)"

CREATEMOD:
	system "CRTCPPMOD MODULE(${BUILDLIB}/ileBridge) SRCSTMF('$(CURDIR)/ileBridge.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(37)" 


CREATEPGM: CREATEMOD
	system "CRTPGM PGM(${BUILDLIB}/ileBridge) MODULE(${BUILDLIB}/ileBridge) ACTGRP(*CALLER)"

CREATEMODK:
	system "CRTCPPMOD MODULE(${BUILDLIB}/ileBridgeK) SRCSTMF('$(CURDIR)/ileBridgeK.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(37)" 



CREATEPGMK: CREATEMODK
	system "CRTPGM PGM(${BUILDLIB}/ileBridgeK) MODULE(${BUILDLIB}/ileBridgeK) ACTGRP(*CALLER)"


CREATECUSTOMERMOD:
	system "CRTCPPMOD MODULE(${BUILDLIB}/ileBridgeC) SRCSTMF('$(CURDIR)/sampleCustomerProgram.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(37)" 
	system "CRTCPPMOD MODULE(${BUILDLIB}/ileBridgeL) SRCSTMF('$(CURDIR)/ileBridgeLib.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(37)" 

CREATECLIB:
	system "CRTCMOD MODULE(${BUILDLIB}/ileLib) SRCSTMF('$(CURDIR)/ileLib.c') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(37)" 

CREATECPGM:
	system "CRTPGM PGM(${BUILDLIB}/ileLibC) MODULE(${BUILDLIB}/ileBridgeC ${BUILDLIB}/ileLib) ACTGRP(*CALLER)"


CREATECUSTOMERPGM: CLEAN CREATECUSTOMERMOD
	system "CRTPGM PGM(${BUILDLIB}/ileBridgeC) MODULE(${BUILDLIB}/ileBridgeC ${BUILDLIB}/ileBridgeL) ACTGRP(*CALLER)"

CREATESRVPGM:
	system "CRTSRVPGM SRVPGM(${BUILDLIB}/ileBridgeS) MODULE(${BUILDLIB}/ileBridgeL) EXPORT(*ALL) ACTGRP(*CALLER)"

CREATECUSTOMERRPG: CREATECUSTOMERMOD
	system "CRTRPGPGM PGM(${BUILDLIB}/TYRICO) SRCFILE(${BUILDLIB}/TYRICO) SRCMBR(CUST) BNDDIR(TYRICO/BNDDIR)"

all: CREATEPGM CREATEPGMK CREATECUSTOMERPGM