BUILDLIB:=TYRICO

CLEAN:
	-system "DLTPGM PGM(${BUILDLIB}/SAMPLECPP)"
	-system "DLTPGM PGM(${BUILDLIB}/SAMPLERPG)"
	-system "DLTMOD MODULE(${BUILDLIB}/SAMPLECPP)"
	-system "DLTMOD MODULE(${BUILDLIB}/SAMPLERPG)"
	-system "DLTMOD MODULE(${BUILDLIB}/TYRICO)"
	-system "DLTSRVPGM SRVPGM(${BUILDLIB}/TYRICO)"



CREATE_TYRICO_MOD:
	system "CRTCPPMOD MODULE(${BUILDLIB}/TYRICO) SRCSTMF('$(CURDIR)/tyrico.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(37)" 

CREATE_SAMPLE_CPP_MOD:
	system "CRTCPPMOD MODULE(${BUILDLIB}/SAMPLECPP) SRCSTMF('$(CURDIR)/sampleCustomerProgram.cpp') OPTION(*EVENTF) SYSIFCOPT(*IFS64IO) DBGVIEW(*SOURCE) TERASPACE(*YES *TSIFC) STGMDL(*SNGLVL) DTAMDL(*p128) DEFINE(DEBUG_ENABLED) OUTPUT(*PRINT) TGTCCSID(37)" 

CREATE_SAMPLE_CPP_PGM: CREATE_SAMPLE_CPP_MOD
	system "CRTPGM PGM(${BUILDLIB}/SAMPLECPP) MODULE(${BUILDLIB}/SAMPLECPP ${BUILDLIB}/TYRICO) ACTGRP(*CALLER)"

CREATE_SAMPLE_RPG_MOD:
	system "CRTRPGMOD MODULE(${BUILDLIB}/SAMPLERPG) srcstmf('/home/jonathan/builds/tyricov2/SAMPLECUST.rpgle') AUT() DBGVIEW(*ALL) OPTIMIZE() OPTION(*EVENTF) OUTPUT(*PRINT) TEXT('') TGTCCSID(*JOB) TGTRLS() INCDIR(*NONE) DEFINE()""

CREATE_SAMPLE_RPG_PGM: CREATE_SAMPLE_RPG_MOD
	system "CRTPGM (${BUILDLIB}/SAMPLERPG)"

CREATE_SRVPGM: CREATE_TYRICO_MOD
	system "CRTSRVPGM SRVPGM(${BUILDLIB}/TYRICO) MODULE(${BUILDLIB}/TYRICO) EXPORT(*ALL) ACTGRP(*CALLER)"


ALL: CLEAN CREATE_SRVPGM CREATE_SAMPLE_RPG_PGM CREATE_SAMPLE_CPP_PGM